let sample = `// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN

android {
  compileOptions {
      sourceCompatibility JavaVersion.VERSION_21
      targetCompatibility JavaVersion.VERSION_21
  }
}

apply from: "../capacitor-cordova-android-plugins/cordova.variables.gradle"
dependencies {

}


if (hasProperty('postBuildExtras')) {
  postBuildExtras()
}
`;

sample = sample.replace(/if \(hasProperty\('postBuildExtras'\)\) \{[\s\S]*?\}/g, '// postBuildExtras removed');
sample = sample.replace(/apply from: [^\n]+/g, (match) => {
  if (match.includes('cordova')) return '// cordova removed';
  return match;
});
console.log('Result:\n' + sample);
